base: &base
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *base
  database: bazasos_development

test:
  <<: *base
  database: bazasos_test

production:
  <<: *base
  database: bazasos_staging

staging:
  <<: *base
  database: bazasos_staging
