base: &base
  adapter: postgresql
  encoding: unicode
  host: '/home/roman/pg'
  port: 5434

development:
  <<: *base
  database: bazasos_development

test:
  <<: *base
  database: bazasos_test

production:
  <<: *base
  database: bazasos

staging:
  encoding: unicode
  adapter: postgtesql
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: bazasos_staging
